[system]
# Load language from environment variable(It is set by the hook)
language = "${env:DBGPT_LANG:-en}"
api_keys = []
encrypt_key = "your_secret_key"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "sqlite"
path = "pilot/meta_data/dbgpt.db"


[rag]
chunk_size=1000
chunk_overlap=0
similarity_top_k=5
similarity_score_threshold=0.0
max_chunks_once_load=10
max_threads=1
rerank_top_k=3

[rag.storage]
[rag.storage.vector]
type = "chroma"
persist_path = "pilot/data"

[rag.storage.graph]
type = "tugraph"
host="192.168.236.129"
port=7687
username="admin"
password="Qwertyuiop@123"

# Model Configurations
#[models]
#[[models.llms]]
#name = "${env:LLM_MODEL_NAME:-gpt-4o}"
#provider = "${env:LLM_MODEL_PROVIDER:-proxy/openai}"
#api_base = "${env:OPENAI_API_BASE:-https://api.openai.com/v1}"
#api_key = "${env:OPENAI_API_KEY}"
#
#[[models.embeddings]]
#name = "${env:EMBEDDING_MODEL_NAME:-text-embedding-3-small}"
#provider = "${env:EMBEDDING_MODEL_PROVIDER:-proxy/openai}"
#api_url = "${env:EMBEDDING_MODEL_API_URL:-https://api.openai.com/v1/embeddings}"
#api_key = "${env:OPENAI_API_KEY}"
[models]

#[[models.llms]]
#name = "${env:LLM_MODEL_NAME:-qwen-vl-max}"
#provider = "${env:LLM_MODEL_PROVIDER:-proxy/openai}"
#api_base = "${env:OPENAI_API_BASE:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
#api_key = "sk-65ac2b2c83db46df8cad5e9bb62454a5"

[[models.llms]]
name = "${env:LLM_MODEL_NAME:-Qwen-72B}"
provider = "${env:LLM_MODEL_PROVIDER:-proxy/openai}"
api_base = "${env:OPENAI_API_BASE:-http://180.153.21.76:17009/v1/}"
api_key = "123"


[[models.llms]]
name = "${env:LLM_MODEL_NAME:-DeepSeek-R1-70B}"
provider = "${env:LLM_MODEL_PROVIDER:-proxy/openai}"
api_base = "${env:OPENAI_API_BASE:-http://172.18.0.1:8080/v1}"
api_key = "sk-1234567890"

[[models.embeddings]]
name = "${env:EMBEDDING_MODEL_NAME:-text-embedding-3-small}"
provider = "${env:EMBEDDING_MODEL_PROVIDER:-proxy/openai}"
api_url = "${env:EMBEDDING_MODEL_API_URL:-http://180.153.21.76:12118/v1/embeddings}"
api_key = "123"

